### PR TITLE
feat: Add `golangci-lint`

### LINKED ISSUE #9: Add `golangci-lint`
## Description

`golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports `yaml` config, has integrations with all major IDE, and has dozens of linters included.

## References

https://golangci-lint.run/

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #9

### CODE REVIEW

**Comment by iamrajiv** [comment]
@ojaswa1942 Please review.

**Review by ojaswa1942 — COMMENTED** [review]
```
golangci-lint found no issues
```
Can you describe what happens when an issue is found? 
Does it auto-fix linting and makes a commit or the action fails?

**Comment by iamrajiv** [comment]
@ojaswa1942 No, it does not auto-fix. It gives you details of where is the error and which file. The reason for not auto-fixing is because it might be a false positive report so we have to check manually too.

**Comment by ojaswa1942** [comment]
No worries @iamrajiv. Can you jot down the steps to enable auto-fix in the linked issue #10, in case we need to enable that in future?

**Comment by iamrajiv** [comment]
@ojaswa1942 no like it does not support auto-fix only. It will check the code and highlight codes that are not linted and after that, we have to edit the code accordingly.

**Comment by ojaswa1942** [comment]
I see. If that's the case, it seems a good idea to add this as a pre-commit hook as well, what do you say? That'll provide feedback proactively at the time of commit instead of PR.

**Comment by iamrajiv** [comment]
@ojaswa1942 pre commit hook you mean it will run when we push code from terminal that time?

**Comment by ojaswa1942** [comment]
Something similar @iamrajiv. At the time of commit. 
A reference which I quickly googled up is [here](https://freshman.tech/linting-golang/#setting-up-a-pre-commit-hook), this should give you a fair idea. Let me know what you think about it.

Please note that the above link is just a random reference and might not be applicable in this case. It is only to give an idea.

**Review by ojaswa1942 — APPROVED** [review]
@iamrajiv I've decided to split this issue into 2. Feel free to pick the new issue #11.   
Thanks for your contribution.  
Happy Hacktoberfest!

**Pull request merged**
